### ISSUE TITLE
npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662                 throw new Error( 'Bad RGB value' ) ;

### ISSUE THREAD

**Issue by adsp16** [zurb/foundation-cli#114]
cant use node verion 12 as I get primoridals errors? 

downgraded node version to 10.0.0 as per discussions on forums. It now install the client but Im getting errors now when running foundation new

C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662

 throw new Error( 'Bad RGB value' ) ;
                ^

Error: Bad RGB value
    at Terminal.registerForRgb (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662:9)
    at Terminal.color256 (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termconfig\xterm.js:280:26)
    at str.replace (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:213:26)
    at String.replace (<anonymous>)
    at Object.format (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:97:12)
    at applyEscape (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:558:47)
    at createOptimized (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:494:43)
    at Object.createTerminal (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:418:2)
    at terminal (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termkit.js:102:18)
    at Object.get [as terminal] (C:\Users\Pricey-razer\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\lazyness\lib\Lazyness.js:48:16)

Please help I am desperate to use foundation

**Comment by shivayanbora123** [comment]
I am having the exact same issue... I am trying to use foundation-cli to create a foundation email project.
C:\Users\1022042\Documents\Github>foundation new --framework emails
C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662
                throw new Error( 'Bad RGB value' ) ;
                ^

Error: Bad RGB value
    at Terminal.registerForRgb (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662:9)
    at Terminal.color256 (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termconfig\xterm.js:280:26)
    at str.replace (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:213:26)
    at String.replace (<anonymous>)
    at Object.format (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:97:12)
    at applyEscape (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:558:47)
    at createOptimized (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:494:43)
    at Object.createTerminal (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:418:2)
    at terminal (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termkit.js:102:18)
    at Object.get [as terminal] (C:\Users\1022042\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\lazyness\lib\Lazyness.js:48:16)

**Comment by sanatan83** [comment]
Hi i am also getting the same error from last 24 hrs, Please fix it.

C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662
                throw new Error( 'Bad RGB value' ) ;
Error: Bad RGB value
    at Terminal.registerForRgb (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662:9)
    at Terminal.color256 (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termconfig\xterm.js:280:26)
    at str.replace (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:213:26)
    at String.replace (<anonymous>)
    at Object.format (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:97:12)
    at applyEscape (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:558:47)
    at createOptimized (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:494:43)
    at Object.createTerminal (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:418:2)
    at terminal (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termkit.js:102:18)
    at Object.get [as terminal] (C:\Users\m1032177\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\lazyness\lib\Lazyness.js:48:16)

**Comment by wbalbinot** [comment]
Apparently this is only happening on Windows. I use a Mac at work and can't see this behaviour there, but at home (windows) it does.

C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662                           throw new Error( 'Bad RGB value' ) ;                                                                                    ^                                                                                                                                                                                                                               Error: Bad RGB value                                                                                                        at Terminal.registerForRgb (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:1662:9)                                                                                                    at Terminal.color256 (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termconfig\xterm.js:280:26)                                                                                                  at str.replace (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:213:26)                                                                                                                    at String.replace (<anonymous>)                                                                                         at Object.format (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:97:12)                                                                                                                   at applyEscape (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:558:47)                                                                                                                at createOptimized (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:494:43)                                                                                                            at Object.createTerminal (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\Terminal.js:418:2)                                                                                                       at terminal (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\terminal-kit\lib\termkit.js:102:18)                                                                                                                    at Object.get [as terminal] (C:\Users\email\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\lazyness\lib\Lazyness.js:48:16)

**Comment by wbalbinot** [comment]
![Annotation 2019-08-03 014650](https://user-images.githubusercontent.com/3904040/62414889-f72d4700-b5f7-11e9-8677-7ccbbfd278a3.png)

No issues with Linux as well, tested on Ubuntu 19.04

**Comment by sanatan83** [comment]
This issue exists on windows, Please help us to fix this issue as soon as possible.
