### ISSUE TITLE
foundation-cli@2.0.0-beta: messages undefined in noRoot check

### ISSUE THREAD

**Issue by kamioftea** [zurb/foundation-cli#15]
/usr/lib/node_modules/foundation-cli/lib/commands/new.js:38
          console.log(util.mascot('sites', messages.noRoot));
                                                   ^
    TypeError: Cannot read property 'noRoot' of undefined
        at preflight (/usr/lib/node_modules/foundation-cli/lib/commands/new.js:38:48)
        at /usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:607:21
        at /usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:246:17
        at iterate (/usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:146:13)
        at async.eachSeries (/usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:162:9)
        at _asyncMap (/usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:245:13)
        at Object.mapSeries (/usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:228:23)
        at Object.async.series (/usr/lib/node_modules/foundation-cli/node_modules/async/lib/async.js:605:19)
        at Object.module.exports [as new] (/usr/lib/node_modules/foundation-cli/lib/commands/new.js:33:9)
        at Object.<anonymous> (/usr/lib/node_modules/foundation-cli/bin/cli.js:68:28)

The issue looks to be that messages is defined in prompt(step 2) once a project has been chosen, but if the app is run as root then preflight(step 1) assumes it is already defined.

**Comment by gakimball** [comment]
Fixed via ae3c2f864d166aa4c367ae225a6a73dc36a73b42
