### ISSUE TITLE
foundation build error

### ISSUE THREAD

**Issue by alexkushner** [zurb/foundation-cli#16]
It seems the new version of the cli is missing the "build" script.  Just tried this both on OSX and Windows with the same result:

`$ foundation build`
`Error: missing script: build`

**Comment by wobbit** [comment]
I get the same: 
```
$ foundation build
Error: missing script: build
    at run (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/run-script.js:142:19)
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/run-script.js:58:5
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
    at checkBinReferences_ (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
    at final (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
    at then (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
    at fs.js:272:14
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:42:10
```

I'm using CLI 2.0.0:

```
$ foundation -v
Foundation CLI version 2.0.0
```

**Comment by gakimball** [comment]
Which project templates are you both using?

**Comment by brnrdbrk** [comment]
Same here, using Foundation for Sites template.

**Comment by wobbit** [comment]
Foundation for Sites here as well. Project was created with Foundation CLI

**Comment by gakimball** [comment]
Looks like that template was missing a proper build script. If you open your project's `package.json`, you can add a new entry to the `scripts` field that will add the missing build command. Here's what it should look like:

```json
"scripts": {
  "start": "gulp",
  "build": "gulp sass"
},
```

That will do a one-time build of the Sass without starting the watching process. With this template, that's the only difference between a `watch` and a `build`. The [ZURB Template](https://github.com/zurb/foundation-zurb-template) has a lot more bells and whistles that go into its build process.

**Comment by gakimball** [comment]
Made this change in the template itself also: [see here](https://github.com/zurb/foundation-sites-template/commit/64e56b023d780bf3c55751b9da1b4dcd628ec661)
