### ISSUE TITLE
gulp watch and foundation watch errors

### ISSUE THREAD

**Issue by car3oon** [zurb/foundation-cli#23]
I've installed newest `foundation-cli` ( `foundation -v` doesn't work, it only shows help info, so i've checked version with `foundation --version` command: `Foundation CLI version 2.0.1`  ) on Ubuntu 15.04. Gulp and foundation watch stop working and throwing error in CLI  as below:

```
$ gulp
[08:42:34] Using gulpfile ~/Workspaces/max-test/gulpfile.js
[08:42:34] Starting 'build'...
[08:42:34] Starting 'clean'...
[08:42:34] Finished 'clean' after 4.51 ms
[08:42:34] Starting 'pages'...
[08:42:34] Starting 'sass'...
[08:42:35] Starting 'javascript'...
[08:42:35] Starting 'images'...
[08:42:35] Starting 'copy'...
[08:42:35] Finished 'images' after 313 ms
[08:42:35] Finished 'pages' after 1.32 s
[08:42:35] Finished 'copy' after 62 ms
[08:42:35] Finished 'javascript' after 585 ms

/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:79:21)
    at DestroyableTransform._transform (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at DestroyableTransform.ondata (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at DestroyableTransform.emit (events.js:95:17)
    at readableAddChunk (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:201:16)
    at DestroyableTransform.Readable.push (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:165:10)
    at DestroyableTransform.Transform.push (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at afterTransform (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:81:12)
    at TransformState.afterTransform (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at filePush (/home/ubuntu_user/Workspaces/max-test/node_modules/gulp-sass/index.js:110:7)

```

**Comment by jacmoe** [comment]
I have this piece of code in my Gulp projects because it sometimes perform wonders:
```
// fix problems with undefined Promise class
// http://stackoverflow.com/questions/32490328/gulp-autoprefixer-throwing-referenceerror-promise-is-not-defined
require('es6-promise').polyfill();
```

**Comment by car3oon** [comment]
Thank you @jacmoe :+1: 
It's working now. Of course had to add it to dev dependencies and  install package before:
`npm install --save-dev es6-promise`

**Comment by jacmoe** [comment]
Wonder performed.
Glad to hear that it allowed you to continue and actually use the Foundation client :)

**Comment by gakimball** [comment]
Your version of Node is probably out of date. The polyfill is adding ES6 features supported by newer versions of Node.

What version do you see with `node -v`?

**Comment by car3oon** [comment]
My Node version is `v0.10.41`. 
Thing is i didn't see any requirement about Node version on github readme.

**Comment by gakimball** [comment]
@car3oon This was a fairly recent thing, so we need to update our requirements. I'll be working on that today.

**Comment by car3oon** [comment]
@gakimball good to hear. And i forgot to thank you for awesome tool!

**Comment by gakimball** [comment]
@car3oon My pleasure, thanks for using it :)
