### ISSUE TITLE
Zurb installation on Windows 7

### ISSUE THREAD

**Issue by 4shoda** [zurb/foundation-cli#27]
I tried the standard site installation on Windows 7 and it worked great. However when I try to create a foundation project for the Zurb Template I get an error. Any help in getting this to install correctly? 
===================
λ foundation new
? What are you building today? A website (Foundation for Sites)
? What's the project called? (no spaces) my-zurb-project
? Which template would you like to use? ZURB Template: includes Handlebars templates and Sass/JS compilers

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/

Downloading the project template...
Done downloading!

Installing dependencies...

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TLSWrap.onread (net.js:544:26)

**Comment by gakimball** [comment]
Looks to be an Internet connection issue. A few possibilities:

- Your connection died partway through the install process.
- You're behind a proxy or firewall of some kind.

Try `cd`ing into the project folder and running `npm install` and see what happens.

**Comment by 4shoda** [comment]
It's odd that I can install the one but not the other though using the foundation cli? (oh and totally not sure why the next paragraph seems to be in a huge font to me). 

So I entered exactly what you said to `npm install` and that gave me a few warnings but no errors. I don't need to tell npm what to install I guess? Sorry, not sure how to format so the warnings appear in a code box or whatever. Would I then just run `foundation watch` or should I use something else? 

=============

G:\BT Webs\+ F6\my-zurb-project  (foundation-zurb-template@1.0.0)
λ npm install
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\style-sherpa\node_modules\handlebars\nod
e_modules\uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\style-sherpa\node_modules\handlebars\nod
e_modules\async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\style-sherpa\node_modules\handlebars\nod
e_modules\uglify-js requires source-map@'~0.5.1' but will load
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\style-sherpa\node_modules\handlebars\nod
e_modules\source-map,
npm WARN unmet dependency which is version 0.4.4
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\style-sherpa\node_modules\handlebars\nod
e_modules\uglify-js requires yargs@'~3.10.0' but will load
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\yargs,
npm WARN unmet dependency which is version 3.32.0
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\browser-sync\node_modules\browser-sync-u
i requires async-each-series@'^1.1.0' but will load
npm WARN unmet dependency G:\BT Webs\+ F6\my-zurb-project\node_modules\browser-sync\node_modules\async-each-ser
ies,
npm WARN unmet dependency which is version 0.1.1

**Comment by gakimball** [comment]
Whenever it says `npm WARN`, you can ignore it. If it says `npm ERR!`, then you've got problems.

When `npm install` finishes, it prints out a big tree of every plugin it installed, that looks something like this. If you got that, then you're good to run `foundation watch`. Or actually, even if you didn't, try running it anyway and see what happens.

```
├─┬ assert-dir-equal@1.0.1 
│ ├── buffer-equal@0.0.0 
│ ├── fs-readdir-recursive@0.0.1 
│ └── is-utf8@0.2.1 
```
