### ISSUE TITLE
foundation watch doesn't working

### ISSUE THREAD

**Issue by wesleyguirra** [zurb/foundation-cli#46]
I'm running the foundation for emails,

when I run the foundation watch command, everything seems ok, I open the localhost:3000 and there is my template, but when I edit the html or sass files, the page doesn't reload or update the content, even if I force the reload, the page keeps same.

I attached a screenshot of terminal running command.

![screen shot 2017-02-22 at 4 27 16 pm](https://cloud.githubusercontent.com/assets/10504265/23228603/f2eba7fe-f91b-11e6-8c3d-478b34b00cf7.png)

**Comment by Leuloch** [comment]
Hello everyone!

My Watch Command doens't work either, but the output is:
```
 forms  foundation watch    

> foundation-zurb-template@1.0.0 start /home/ednei/Projects/forms
> gulp

[07:52:10] Requiring external module babel-register
[07:54:44] Using gulpfile ~/Projects/forms/gulpfile.babel.js
[07:54:44] Starting 'default'...
[07:54:44] Starting 'build'...
[07:54:44] Starting 'clean'...
[07:54:44] Finished 'clean' after 32 ms
[07:54:44] Starting 'pages'...
[07:54:44] Starting 'sass'...
[07:54:44] Starting 'javascript'...
[07:54:44] Starting 'images'...
[07:54:44] Starting 'copy'...
[07:55:48] Finished 'images' after 1.07 min
[07:55:57] Finished 'pages' after 1.22 min
[07:55:58] Finished 'copy' after 1.22 min
[07:56:00] Finished 'sass' after 1.27 min
[07:56:05] Finished 'javascript' after 1.33 min
[07:56:05] Starting 'styleGuide'...
[07:56:05] Finished 'styleGuide' after 130 ms
[07:56:05] Finished 'build' after 1.35 min
[07:56:05] Starting 'server'...
[07:56:10] Finished 'server' after 5.19 s
[07:56:10] Starting 'watch'...
[07:56:11] 'watch' errored after 666 ms
[07:56:11] Error: watch src/assets ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/ednei/Projects/forms/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ednei/Projects/forms/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ednei/Projects/forms/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/ednei/Projects/forms/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/ednei/Projects/forms/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/ednei/Projects/forms/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
[07:56:11] 'default' errored after 1.43 min
Error: foundation-zurb-template@1.0.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (/home/ednei/.npm-global/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/lifecycle.js:217:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/home/ednei/.npm-global/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/spawn.js:24:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
I'm using node version 6.10.0 and npm version 3.10.10 in a Ubuntu 16.04 environment.

**Comment by ahb360** [comment]
I have this problem too. I changed the layout and after that this error appeared.
![foundation problem](https://cloud.githubusercontent.com/assets/937130/26139545/ac1d8538-3ae6-11e7-8de5-2b514367dca5.png)

**Comment by Gabrielnz** [comment]
I have the same problem.

**Comment by benjamin-sh** [comment]
Look this page it's works for me [https://discourse.roots.io/t/gulp-watch-error-on-ubuntu-14-04-solved/3453](url)

**Comment by ryangallaher** [comment]
It looks like the link benjamin-sh shared with a solution has died. Has anyone else had any luck resolving this? I haven't even changed anything in my Zurb stack project.

**Comment by PieterBuitenga** [comment]
As per benjamin-sh link.... The reason for the error is there is a limit in the system for how many files can be watched by a user. This can be increased by putting the following in a terminal window

echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
