### ISSUE TITLE
"foundation blocks" fails

### ISSUE THREAD

**Issue by macmedia** [zurb/foundation-cli#53]
When I run ```foundation blocks``` or ```foundation kits``` I receive an error that **"fn is not a function"**. Here is the complete message.

```
/usr/local/lib/node_modules/foundation-cli/lib/commands/kits.js:16
  fn(args.slice(1), options, callback);
  ^

TypeError: fn is not a function
    at Object.module.exports [as kits] (/usr/local/lib/node_modules/foundation-cli/lib/commands/kits.js:16:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/bin/foundation.js:61:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

Other commands like ```foundation new``` and ```foundation watch``` work fine.

## System:
- OSX: 10.12.4
- Node: v7.8.0
- NPM: 4.2.0
- Foundation-CLI: Foundation CLI version 2.2.0

**Comment by macmedia** [comment]
Looks like I was missing the **_list_** argument.

```foundation blocks list```
