### ISSUE TITLE
git error vague on 'foundation new'

### ISSUE THREAD

**Issue by pbonnell** [zurb/foundation-cli#54]
git is fully configured and functional on the system, but **foundation new** fails with:

> Downloading the project template...There was an issue running git clone to download the....
Make sure your computer's Git is configured properly and then try again.

looks like it's the result of [this clone command](https://github.com/zurb/foundation-cli/blob/e0484a4b49d5ebf4b133121e8d136004855a6a3a/lib/commands/new.js#L70)

Error should be more specific about the nature of the failure.
_**Does git need a symlink?**_

osx 10.11.6
```
$ foundation --version
Foundation CLI version 2.2.0
$ npm --version
3.9.5
$ node --version
v6.2.2
$ git --version
git version 2.2.1
$ which git
/usr/local/git/bin/git
```

**Comment by pbonnell** [comment]
console.log(err) here yields :
```
Downloading the project template...{ Error: Command failed: git clone https://github.com/zurb/foundation-apps-template.git test
Cloning into 'test'...
fatal: Unable to find remote helper for 'https'

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git clone https://github.com/zurb/foundation-apps-template.git test' }
There was an issue running git clone to download the framework Foundation for apps and template unspecified.
```

**Comment by paxperscientiam** [comment]
Hello @pbonnell 

Are you using commit `df9bad2`?

I just tried the following commands without error (in my test environment):
````bash
foundation new -f apps
````

Are you still getting this error? What about with the latest committ (v2.2.1)? -- `ec8f72b`

**Comment by pbonnell** [comment]
ty @paxperscientiam,
I'm up and running after a re-install of npm (4.5.0), then fresh install of foundation-cli (now 2.2.1).
I've chalked this to system config confusion, though a more meaningful error from foundation install would have been ideal.

I originally installed via 
```npm install foundation-cli```
 foundation v.2.2.0 for the failing install is all the info I have.

Regardless, the original problem seems local config specific.
