### ISSUE TITLE
Watch error after updating CLI

### ISSUE THREAD

**Issue by MichaelJPDX** [zurb/foundation-cli#68]
Noticed there was a CLI update available (current 2.2.1, new 2.2.3) but after updating through npm I get the following error trying to run watch in a project:

```
/usr/local/lib/node_modules/foundation-cli/lib/commands/info.js:7
module.exports = function(args = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/lib/index.js:4:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I noticed some warnings about bower and terminal-kit when I updated, but it appeared to complete okay. Any idea how to fix this?

**Comment by bpcoxjr** [comment]
I am getting the same error.  I thought it might have been an issue on my Mac, so I uninstalled/reinstalled Node and NPM, and the CLI, but am still getting the same error. Tried on a secondary Mac and am getting the same error.

**Comment by kball** [comment]
Hey @MichaelJPDX and @bpcoxjr -thanks for the bug report! Can ya'all let us know what version of node you're using? (CC @paxperscientiam)

**Comment by bpcoxjr** [comment]
Thanks for the quick response @kball.  I'm running node v4.5.0 on both of my machines.

**Comment by kball** [comment]
I'm able to reproduce this bug in 4.5.0... it works find in 6 series, so this is probably a feature of ES2016 that wasn't supported in earlier node versions.  @paxperscientiam can you take a look at fixing?

@bpcoxjr a workaround in the meantime would be to update to 6 series node... for what it's work, I use (and highly recommend) nvm (https://github.com/creationix/nvm) to manage multiple node versions

**Comment by bpcoxjr** [comment]
Thanks @kball.  I downloaded NVM and changed the version of node I was operating on it works now!

**Comment by MichaelJPDX** [comment]
Looks like I've got 4.6.1.  I'll try upgrading. Thanks for the help!

**Comment by bpcoxjr** [comment]
Hang on a second @kball.  The 'foundation new' command works okay, but when I cd into that folder and run 'foundation watch' it stops at the default task and just hangs there doing nothing.

**Comment by paxperscientiam** [comment]
Hi @kball I'm using a pretty recent version -- node v7.10.0

**Comment by Moonbase59** [comment]
Same error here (Ubuntu 14.04.5 LTS and Linux Mint 17.3), node 4.8.3 installed from distro repos.
I was trying to upgrade foundation-cli from 2.2.2 to 2.2.3.
I still have several Foundation 6.2/6.3 based sites, what will break if I upgrade Node?
