### ISSUE TITLE
Latest Release is Not Working

### ISSUE THREAD

**Issue by billyromano** [zurb/foundation-cli#89]
Just running the `foundation` command throws an error. I've uninstalled and reinstalled the package and it still doesn't work.

```/Users/uwxr701/.npm-packages/lib/node_modules/foundation-cli/lib/commands/info.js:7
module.exports = function(args = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/billy/.npm-packages/lib/node_modules/foundation-cli/lib/index.js:4:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)```

**Comment by billyromano** [comment]
Resolved from this reference: https://github.com/zurb/foundation-cli/issues/68#issuecomment-304382938
